sudo: required
language: elixir
elixir:
  - 1.10
opt_release:
  - 22.2.6

addons:
  postgres: "9.4"

services:
  - postgresql

cache:
  directories:
    - _build
    - deps

script:
  - mix format --check-formatted --dry-run
  - mix credo --strict
  - mix sobelow --config
  - mix coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy_deploy:
  - curl https://sdk.cloud.google.com | bash > /dev/null #Download SDK GOOGLE
  - source "$HOME/google-cloud-sdk/path.bash.inc"
  - gcloud auth activate-service-account --key-file=google-key.json
  - gcloud auth configure-docker # habilita push para o gcr
  - gcloud config set project "${GCP_PROJECT_ID}"
  - gcloud components install beta # until Cloud Run is generally available (GA)
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
