name: CI-ELXPRo

on: pull_request

jobs:
  lint:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        otp-version: '23.0'
        elixir-version: '1.10.1'

    - uses: actions/cache@v2
      env:
        cache-name: cache-elixir-deps
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
                    ${{ runner.os }}-build-${{ env.cache-name }}-
                    ${{ runner.os }}-build-
                    ${{ runner.os }}-
    - name: deps
      run: mix deps.get
    - name: LINT CODE
      run: mix credo --strict

  check_format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        otp-version: '23.0'
        elixir-version: '1.10.1'

    - uses: actions/cache@v2
      env:
        cache-name: cache-elixir-deps
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
                    ${{ runner.os }}-build-${{ env.cache-name }}-
                    ${{ runner.os }}-build-
                    ${{ runner.os }}-
    - name: deps
      run: mix deps.get
    - name: Format
      run: mix format --check-formatted

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        otp-version: '23.0'
        elixir-version: '1.10.1'

    - uses: actions/cache@v2
      env:
        cache-name: cache-elixir-deps
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
                    ${{ runner.os }}-build-${{ env.cache-name }}-
                    ${{ runner.os }}-build-
                    ${{ runner.os }}-
    - name: deps
      run: mix deps.get
    - name: Format
      run: mix sobelow --config

  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-elixir@885971a72ed1f9240973bd92ab57af8c1aa68f24
      with:
        otp-version: '23.0'
        elixir-version: '1.10.1'

    - uses: actions/cache@v2
      env:
        cache-name: cache-elixir-deps
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
                    ${{ runner.os }}-build-${{ env.cache-name }}-
                    ${{ runner.os }}-build-
                    ${{ runner.os }}-
    - name: codecov quality
      run: mix coveralls.json
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN}}

  deploy:
    # needs: test # Will only run if the test job succeeds
    if: github.ref == 'refs/heads/master' # Only run this job if it is on the main branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master # Checkout out master instead of the latest commit
          fetch-depth: 0 # Checkout the whole branch

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.1

      - uses: mhanberg/gigalixir-action@<current release>
        with:
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          GIGALIXIR_APP: wet-boring-hackee # Feel free to also put this in your secrets
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          MIGRATIONS: false  # defaults to true
